### ISSUE TITLE
Problem in isClosed() method

### ISSUE THREAD

**Issue by trigchen** [rm5248/JavaSerial#12]
A similar issure as I pointed out in JSSC:
https://github.com/scream3r/java-simple-serial-connector/issues/123

**Comment by rm5248** [comment]
Is this in Windows, Linux, Mac, or multiple ones?  I'll take a look at it in a bit; I thought this was working properly before.

**Comment by trigchen** [comment]
Windows 7.

Best regards,

Trig

2018-03-28 9:41 GMT+08:00 Robert Middleton <notifications@github.com>:

**Comment by rm5248** [comment]
I just tested this on my system, and pulling the cable while it is trying to read results in an `IOException`, which while not ideal is at least a reasonable thing to happen.  

I should have a fix for this shortly.
