### ISSUE TITLE
there is a fatal bug!

### ISSUE THREAD

**Issue by xuebaodev** [rm5248/JavaSerial#13]
when you send data,this JavaSerial sometime will receive 4 time as i send.
like:
when send  AA BB CC . it will receive  AA BB CC AA BB CC AA BB CC AA BB CC 。mostly ,when set 128 bytes recve buffer .it will fill ful of that buffer with AA BB CC....

**Comment by rm5248** [comment]
Closing as there is no new information about this bug.
