### ISSUE TITLE
GetSerialPorts returning Empty

### ISSUE THREAD

**Issue by cbaser** [rm5248/JavaSerial#15]
Hello,
Thank you for this library.
I want to get every serial port of my system and save it in somewhere. 

`String[] ports = SerialPort.getSerialPorts();`

always return empty;
How I can fix that?

I used 

> <dependency>
>     <groupId>com.rm5248</groupId>
>     <artifactId>JavaSerial</artifactId>
>     <version>0.9</version>
> </dependency>

**Comment by rm5248** [comment]
What OS are you on? If you're using a Debian-based version of Linux, the reason you don't get anything back is probably due to a permissions issue.

**Comment by rm5248** [comment]
Closing this issue as there is no new information about what is happening.  If there is new information, I will re-open.
