### ISSUE TITLE
Way to enumerate the ports (Not a bug but a question)

### ISSUE THREAD

**Issue by brianreinhold** [rm5248/JavaSerial#27]
Is there a way to enumerate the serial ports on the system? I would like my app to find the correct serial port without user engagement.

I have no idea what the names of the serial ports could be. Better to find all and analyze each one to see which one is correct.

Thanks

**Comment by rm5248** [comment]
[Yes](https://github.com/rm5248/JavaSerial/blob/1fc9e3052eb48e597542f743804ead314b8a204a/src/com/rm5248/serial/SerialPort.java#L1364)
