### ISSUE TITLE
Way to enumerate the ports (Not a bug but a question) This time with a better answer than 'yes'

### ISSUE THREAD

**Issue by brianreinhold** [rm5248/JavaSerial#28]
Is there a way to enumerate the serial ports on the system? I would like my app to find the correct serial port without user engagement.

I have no idea what the names of the serial ports could be. Better to find all and analyze each one to see which one is correct.

I see an answer 'yes' and then closed. Not helpful. From the Javadoc API there is no clear way to do it.

In the jserialComm library there is a method

SerialPort.getCommPorts()

where I do not have to provide a name (which I do not know).

**Comment by rm5248** [comment]
[You use SerialPort.getSerialPorts() as shown in the javadoc API.  Click here for more information.](https://github.com/rm5248/JavaSerial/blob/1fc9e3052eb48e597542f743804ead314b8a204a/src/com/rm5248/serial/SerialPort.java#L1364)

**Comment by brianreinhold** [comment]
THanks!
