### ISSUE TITLE
Is there a way to get a plug-in event or must I poll? ( A question, not a bug)

### ISSUE THREAD

**Issue by brianreinhold** [rm5248/JavaSerial#29]
Is there a way to receive an event when a device is connected (plugged in) or do I need to poll - periodically call SerialPort.getSerialPorts()?

**Comment by rm5248** [comment]
There is no way to do this apart from polling.

**Comment by brianreinhold** [comment]
Thank you

**Comment by brianreinhold** [comment]
How about a frequently asked questions page instead of issues?

**Comment by rm5248** [comment]
discussions have been enabled.

**Comment by brianreinhold** [comment]
Oh, cool. I should have put my questions there.
