### ISSUE TITLE
open: No such device or address

### ISSUE THREAD

**Issue by vinicioswentz** [rm5248/JavaSerial#5]
I'm trying list the available ports on my system, but I'm getting this error.

The Error:
`open: No such device or address
ERROR: This is a very bad thing that should never happen SerialPortImpl.c:1724  errno:22
open: No such device or address
ERROR: This is a very bad thing that should never happen SerialPortImpl.c:1724  errno:6`

The code:
```

 import com.rm5248.serial.SerialPort;

import java.util.Arrays;
import java.util.List;

public class ReadingFromPortTest {
  public static void main(String[] args) {

    List<String> serialPorts = Arrays.asList(SerialPort.getSerialPorts());
    serialPorts.forEach(System.out::println);
  }
}

```
Any idea what it might be?

**Comment by rm5248** [comment]
I assume that you've fixed this - was this just a permissions problem?  I just want to try and make sure I understand exactly what was going on in case this happens again.

**Comment by vinicioswentz** [comment]
Yes, I fixed, is permission problem, thanks
